In [1]:
import numpy as np

In [8]:
arr1=np.array([[1,6],
               [2,8],
               [3,11],
               [3,10],
               [1,7]])

In [9]:
print(arr1)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [12]:
print("{}".format(arr1.mean(axis=0)))

[ 2.   8.4]


In [13]:
mean_a=arr1.mean(axis=0)

In [14]:
print(mean_a)

[ 2.   8.4]


In [16]:
a_cencered=arr1-mean_a

In [17]:
print(a_cencered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [26]:
a_cencered_sp=a_cencered[0][0]*a_cencered[0][1]+a_cencered[1][0]*a_cencered[1][1]+a_cencered[2][0]*a_cencered[2][1]+a_cencered[3][0]*a_cencered[3][1]+a_cencered[4][0]*a_cencered[4][1]

In [27]:
print(a_cencered_sp)

8.0


In [28]:
print(a_cencered_sp/4)

2.0


In [29]:
a_t=arr1.T

In [30]:
print(a_t)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [31]:
mcv=np.cov(a_t)

In [32]:
print(mcv)

[[ 1.   2. ]
 [ 2.   4.3]]
